# Generated by Django 2.2.6 on 2019-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='realtor_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='seen',
            field=models.BooleanField(default=True),
        ),
    ]
