# Generated by Django 2.2.6 on 2019-11-07 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20191102_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 7, 6, 33, 55, 983066)),
        ),
    ]
