# Generated by Django 2.2.6 on 2019-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_merge_20191113_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
