# Generated by Django 2.2.6 on 2019-11-07 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.IntegerField()),
                ('time', models.TimeField(default=datetime.datetime(2019, 11, 7, 6, 33, 55, 981084))),
            ],
        ),
    ]
