# Generated by Django 2.2.6 on 2019-11-08 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 11, 8, 18, 29, 39, 766420)),
        ),
    ]
