# Generated by Django 2.2.6 on 2019-11-11 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191111_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 11, 11, 8, 38, 35, 891241)),
        ),
    ]
