# Generated by Django 2.2.6 on 2019-11-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191111_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
