# Generated by Django 2.2.6 on 2019-11-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191111_0842'),
        ('accounts', '0002_auto_20191108_1829'),
    ]

    operations = [
    ]
