# Generated by Django 2.2.6 on 2019-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20191113_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
