# Generated by Django 2.2.6 on 2019-11-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_auto_20191108_1829'),
        ('realtors', '0006_auto_20191111_0838'),
    ]

    operations = [
    ]
